# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrRqQ_jV1k7zivKYA83iROwuuN4PZx9P
"""

import streamlit as st
import plotly.graph_objects as go
import numpy as np
import pandas as pd

# Dados
dados = {
    "Passes bons": 24,
    "Passes fracos": 3,
    "Assistências": 2,
    "Dribles": 2,
    "Roubadas de bola": 11,
    "Tentativas de finalização": 4,
    "Chutes altos": 3,
    "Chutes fracos": 3,
    "Defesas na área": 3,
    "Escanteios": 2,
    "Lançamentos da goleira": 3,
}

# Título do Dashboard
st.title("Dashboard de Desempenho da Atleta")

# Gráfico de Radar
st.header("Radar de Desempenho")
categorias = list(dados.keys())
valores = list(dados.values())
fig_radar = go.Figure()
fig_radar.add_trace(go.Scatterpolar(
    r=valores + [valores[0]],
    theta=categorias + [categorias[0]],
    fill="toself",
    name="Desempenho da Atleta",
    line=dict(color="blue")
))
fig_radar.update_layout(
    polar=dict(radialaxis=dict(visible=True)),
    showlegend=True,
    title="Radar de Desempenho"
)
st.plotly_chart(fig_radar)

# Heatmap da Quadra
st.header("Heatmap da Movimentação")
largura = 25
comprimento = 42
posicoes = [
    (5, 5), (10, 10), (12, 15), (15, 20), (18, 22), (10, 30), (7, 35), (12, 38),
    (5, 20), (20, 5), (22, 10), (15, 15), (10, 22), (18, 30), (5, 38)
]
heatmap_data = np.zeros((comprimento, largura))
for x, y in posicoes:
    heatmap_data[y, x] += 1
st.write("Mapa de calor da movimentação da atleta na quadra:")
st.pyplot(sns.heatmap(heatmap_data, cmap="Reds", cbar=True, linewidths=0.5).figure)

# Gráfico de Barras
st.header("Desempenho em Ações Específicas")
labels = ["Passes Bons", "Passes Fracos", "Assistências", "Dribles", "Roubos de Bola"]
valores_bar = [24, 3, 2, 2, 11]
fig_bar = go.Figure(data=go.Bar(
    x=labels,
    y=valores_bar,
    marker_color=["green", "red", "blue", "orange", "purple"]
))
fig_bar.update_layout(
    title="Desempenho em Ações Específicas",
    xaxis=dict(title="Categorias"),
    yaxis=dict(title="Quantidade")
)
st.plotly_chart(fig_bar)

# Gráfico de Pizza
st.header("Distribuição dos Tipos de Finalização")
finalizacoes = {
    "Chutes Altos": 3,
    "Chutes Fracos": 3,
}
labels_pie = list(finalizacoes.keys())
valores_pie = list(finalizacoes.values())
fig_pie = go.Figure(data=go.Pie(
    labels=labels_pie,
    values=valores_pie,
    hole=0.3,
    marker_colors=["red", "blue"]
))
fig_pie.update_layout(
    title="Distribuição dos Tipos de Finalização"
)
st.plotly_chart(fig_pie)